// Data Service with Mock Initializer & Store (§10)
import { Event, Speaker, TeamMember, Notice, Sponsor, Project, Blog, Gallery, LeaderboardEntry, Winner, Certificate } from '@/types';

export const INITIAL_EVENTS: Event[] = [
  {
    id: 'evt_azure_01',
    eventId: 'evt_azure_01',
    title: 'Azure Cloud Architecture & Serverless Masterclass',
    slug: 'azure-cloud-architecture-masterclass',
    shortDescription: 'Hands-on intensive workshop on building serverless microservices with Azure Functions and Cosmos DB.',
    description: 'Join Microsoft Student Ambassadors and industry experts for a 1-day deep dive into modern cloud architecture. Learn Azure Static Web Apps, Cosmos DB, Bicep IAC, and real-time event routing.',
    banner: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80',
    category: 'Workshop',
    mode: 'Offline',
    venue: 'Seminar Hall 4, Main Campus, Marwadi University',
    startDate: '2026-08-25T09:30:00.000Z',
    endDate: '2026-08-25T16:30:00.000Z',
    registrationStart: '2026-08-01T00:00:00.000Z',
    registrationEnd: '2026-08-24T23:59:59.000Z',
    capacity: 150,
    remainingSeats: 18,
    waitlistEnabled: true,
    waitlistLimit: 50,
    waitlistCount: 12,
    registrationStatus: 'Open',
    eventStatus: 'Registration Open',
    speakerIds: ['spk_01', 'spk_02'],
    coordinatorIds: ['tm_01', 'tm_02'],
    sponsorIds: ['spn_01'],
    resourceFolder: 'azure-workshop-2026',
    galleryAlbumId: 'alb_01',
    tags: ['Azure', 'Serverless', 'CosmosDB', 'TypeScript', 'Cloud'],
    agenda: [
      { id: 'ag_1', time: '09:30 AM', title: 'Registration & Welcome Keynote', speaker: 'Prof. Amit Patel', room: 'Hall 4', duration: '30 mins', sessionType: 'Keynote' },
      { id: 'ag_2', time: '10:00 AM', title: 'Serverless Functions in Action', speaker: 'Rahul Sharma', room: 'Lab 204', duration: '90 mins', sessionType: 'Hands-on' },
      { id: 'ag_3', time: '12:00 PM', title: 'Cosmos DB NoSQL Schema Design', speaker: 'Priya Mehta', room: 'Lab 204', duration: '60 mins', sessionType: 'Hands-on' },
      { id: 'ag_4', time: '02:00 PM', title: 'Deploying Azure Static Web Apps', speaker: 'Rahul Sharma', room: 'Lab 204', duration: '120 mins', sessionType: 'Hands-on' },
      { id: 'ag_5', time: '04:00 PM', title: 'Q&A, Quiz & Certificate Distribution', speaker: 'Team MCC', room: 'Hall 4', duration: '30 mins', sessionType: 'Quiz' }
    ],
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'published'
  },
  {
    id: 'evt_hack_01',
    eventId: 'evt_hack_01',
    title: 'National Azure AI Hackathon 2026',
    slug: 'national-azure-ai-hackathon-2026',
    shortDescription: '36-hour nationwide hackathon building next-gen AI applications with OpenAI & Azure Services.',
    description: 'Compete with 500+ student developers across India. Build innovative generative AI solutions for healthcare, education, sustainability, and fintech with mentorship from Microsoft MVPs.',
    banner: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&auto=format&fit=crop&q=80',
    category: 'Hackathon',
    mode: 'Hybrid',
    venue: 'Innovation Center & Online (Teams)',
    startDate: '2026-09-15T09:00:00.000Z',
    endDate: '2026-09-16T21:00:00.000Z',
    registrationStart: '2026-08-10T00:00:00.000Z',
    registrationEnd: '2026-09-10T23:59:59.000Z',
    capacity: 300,
    remainingSeats: 85,
    waitlistEnabled: true,
    waitlistLimit: 100,
    waitlistCount: 0,
    registrationStatus: 'Open',
    eventStatus: 'Registration Open',
    speakerIds: ['spk_01', 'spk_03'],
    coordinatorIds: ['tm_01', 'tm_03'],
    sponsorIds: ['spn_01', 'spn_02'],
    tags: ['AI', 'AzureOpenAI', 'Hackathon', 'Python', 'Next.js'],
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'published'
  },
  {
    id: 'evt_bootcamp_01',
    eventId: 'evt_bootcamp_01',
    title: 'GitHub & Open Source Development Bootcamp',
    slug: 'github-open-source-bootcamp',
    shortDescription: 'Learn Git branching, pull requests, CI/CD with GitHub Actions, and license compliance.',
    description: 'Master Git workflows, open-source contribution practices, code review standards, and GitHub Copilot productivity tips.',
    banner: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=1200&auto=format&fit=crop&q=80',
    category: 'Bootcamp',
    mode: 'Offline',
    venue: 'Auditorium A, Technology Building',
    startDate: '2026-07-20T10:00:00.000Z',
    endDate: '2026-07-20T17:00:00.000Z',
    registrationStart: '2026-07-01T00:00:00.000Z',
    registrationEnd: '2026-07-19T23:59:59.000Z',
    capacity: 200,
    remainingSeats: 0,
    waitlistEnabled: true,
    waitlistLimit: 50,
    waitlistCount: 34,
    registrationStatus: 'Closed',
    eventStatus: 'Completed',
    speakerIds: ['spk_02'],
    coordinatorIds: ['tm_02'],
    sponsorIds: ['spn_01'],
    tags: ['GitHub', 'Git', 'DevOps', 'OpenSource'],
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'published'
  }
];

export const INITIAL_SPEAKERS: Speaker[] = [
  {
    id: 'spk_01',
    speakerId: 'spk_01',
    name: 'Dr. Rajesh Solanki',
    organization: 'Microsoft India',
    designation: 'Principal Cloud Solution Architect',
    bio: 'Experienced cloud architect specializing in distributed systems, Cosmos DB, and AI infrastructure. Over 15 years in software engineering.',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    linkedin: 'rajeshsolanki-msft',
    website: 'https://rajeshsolanki.io',
    expertise: ['Cloud Architecture', 'Azure Cosmos DB', 'Microservices', 'Distributed Systems'],
    eventIds: ['evt_azure_01', 'evt_hack_01'],
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active'
  },
  {
    id: 'spk_02',
    speakerId: 'spk_02',
    name: 'Priya Mehta',
    organization: 'GitHub Tech Lead',
    designation: 'Senior Developer Relations Engineer',
    bio: 'Advocate for open source software, developer tooling, and modern JavaScript ecosystem. Speaker at 50+ international conferences.',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    linkedin: 'priyamehta-github',
    website: 'https://priya.dev',
    expertise: ['GitHub Actions', 'TypeScript', 'DevOps', 'WebAssembly'],
    eventIds: ['evt_azure_01', 'evt_bootcamp_01'],
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active'
  }
];

export const INITIAL_TEAM: TeamMember[] = [
  {
    id: 'tm_01',
    memberId: 'tm_01',
    name: 'Prof. Dr. Amit Patel',
    position: 'Faculty Coordinator',
    department: 'Computer Engineering Dept.',
    category: 'Faculty Coordinators',
    bio: 'Head of Computer Engineering Department at Marwadi University. Guiding student innovation and tech clubs.',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    skills: ['Leadership', 'Cloud Infrastructure', 'Academic Excellence'],
    quote: 'Empowering future tech leaders through hands-on community engagement.',
    email: 'amit.patel@marwadiuniversity.ac.in',
    displayOrder: 1,
    isFeaturedHomepage: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active'
  },
  {
    id: 'tm_02',
    memberId: 'tm_02',
    name: 'Rahul Sharma',
    position: 'President',
    department: 'Computer Engineering (3rd Year)',
    category: 'President',
    bio: 'Gold Microsoft Learn Student Ambassador. Passionate about building cloud native full-stack applications.',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    skills: ['Next.js', 'Azure', 'TypeScript', 'Event Management'],
    quote: 'Building Gujarat’s premier student tech community at Marwadi University.',
    github: 'rahulsharma-mu',
    linkedin: 'rahulsharma-dev',
    displayOrder: 2,
    isFeaturedHomepage: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active'
  },
  {
    id: 'tm_03',
    memberId: 'tm_03',
    name: 'Ananya Verma',
    position: 'Vice President',
    department: 'Information Technology (3rd Year)',
    category: 'Vice President',
    bio: 'ML Ambassador & Community Organizer. Spearheading hackathons and open-source bootcamps.',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
    skills: ['Python', 'Machine Learning', 'Community Outreach'],
    quote: 'Fostering diversity and innovation in tech.',
    github: 'ananya-verma',
    linkedin: 'ananyaverma',
    displayOrder: 3,
    isFeaturedHomepage: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active'
  }
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'ntc_01',
    noticeId: 'ntc_01',
    title: 'Registration Open for Azure Cloud Masterclass',
    description: 'Limited 150 seats available. Register early to receive free Azure pass credits and official certificates.',
    priority: 'Urgent',
    publishDate: '2026-08-05T00:00:00.000Z',
    expiryDate: '2026-08-25T00:00:00.000Z',
    isPinned: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active'
  },
  {
    id: 'ntc_02',
    noticeId: 'ntc_02',
    title: 'MCC Core Team Recruitment 2026-27 Announced',
    description: 'Applications are now open for Technical, Media, Content, and Event Management leads. Apply via Join Us tab.',
    priority: 'Recruitment',
    publishDate: '2026-08-01T00:00:00.000Z',
    isPinned: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active'
  }
];

export const INITIAL_SPONSORS: Sponsor[] = [
  {
    id: 'spn_01',
    sponsorId: 'spn_01',
    name: 'Microsoft for Startups',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    website: 'https://startups.microsoft.com',
    description: 'Providing Azure credits and technical sponsorship for MCC workshops.',
    tier: 'Title',
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active'
  },
  {
    id: 'spn_02',
    sponsorId: 'spn_02',
    name: 'GitHub Education',
    logo: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=200&auto=format&fit=crop&q=80',
    website: 'https://education.github.com',
    description: 'Official student developer pack & swag sponsor for national hackathons.',
    tier: 'Platinum',
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active'
  }
];
